{% set name = "hypothesis" %}
{% set version = "6.152.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/bf/a5/7c66caf83d51b0b8bba1aca94e34c3ae4ff36d58dfd6432d9b29bcf5ce2f/hypothesis-{{ version }}.tar.gz
  sha256: d6e7a3b163ee7f951a2652cfa26ea4c5ff5e94afcdfcaccf1ed72f0435276ff4

build:
  entry_points:
    - hypothesis = hypothesis.extra.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0
    - sortedcontainers >=2.1.0,<3.0.0
    - setuptools
    # Optional but nice to have
    - click >=7.0

test:
  requires:
    - django
    - pandas
    - pip
    - python {{ python_min }}
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - pip check
    - hypothesis --help

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: A library for property based testing

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
