{% set version = "3.33.0" %}

package:
  name: hypothesis
  version: {{version}}

source:
  fn: hypothesis-{{version}}.tar.gz
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{version}}.tar.gz
  md5: cb0ee54fa6b16d5b6c95b7f096f15667

build:
  noarch: python
  number: 1
  script: python setup.py install --optimize=1 --single-version-externally-managed --record record.txt
  
requirements:
  build:
    - python
    - setuptools
    - attrs
    - coverage
  run:
    - python
    - enum34  # [py<34]
    - attrs
    - coverage
    
test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.searchstrategy
    - hypothesis.tools
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - git clone --depth 1 https://github.com/HypothesisWorks/hypothesis-python.git git_src
    - cd git_src
    - python -m pytest tests/cover

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
