{% set name = "hypothesis" %}
{% set version = "6.153.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c5/12/79d2df37e29068bac7f87984635145b856c54492ac0d022402c2c8dc20c5/hypothesis-{{ version }}.tar.gz
  sha256: 906b113721d3ef4f1a87fc9b429cf8f9e2955ef2348eb5b19c476be3bdb6e2fc

build:
  entry_points:
    - hypothesis = hypothesis.extra.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0
    - sortedcontainers >=2.1.0,<3.0.0
    - setuptools
    # Optional but nice to have
    - click >=7.0

test:
  requires:
    - django
    - pandas
    - pip
    - python {{ python_min }}
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - pip check
    - hypothesis --help

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: A library for property based testing

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
