{% set name = "hypothesis" %}
{% set version = "6.56.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypothesis-{{ version }}.tar.gz
  sha256: 15dae5d993339aefa57e00f5cb5a5817ff300eeb661d96d1c9d094eb62b04c9a

build:
  entry_points:
    - hypothesis = hypothesis.extra.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - attrs >=19.2.0
    # exceptiongroup is rc still and should be only [py<311] but let's see if we can keep this noarch.
    - exceptiongroup >=1.0.0rc8
    - sortedcontainers >=2.1.0,<3.0.0
    - backports.zoneinfo >=0.2.1  # [py<39]
    - setuptools
    # Optional but nice to have
    - click >=7.0

test:
  requires:
    - django
    - pandas
    - pip
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    # Skip on Windows and py37 as django has a missing dependency there
    - pip check  # [not win]
    - hypothesis --help

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: A library for property based testing

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
