{% set name = "hypothesis" %}
{% set version = "6.152.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/3b/fb/a5651eb0cd03ecee644e8f4d8cd2027b40a08bf1488f46201e794aebe9b5/hypothesis-{{ version }}.tar.gz
  sha256: de4711d69ce3a18009047c3b44882810fd0c0348c1558e920a4b0d2c45f59e1e

build:
  entry_points:
    - hypothesis = hypothesis.extra.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0
    - sortedcontainers >=2.1.0,<3.0.0
    - setuptools
    # Optional but nice to have
    - click >=7.0

test:
  requires:
    - django
    - pandas
    - pip
    - python {{ python_min }}
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - pip check
    - hypothesis --help

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: A library for property based testing

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
