{% set pkgname = "hypothesis" %}
{% set version = "3.33.0" %}
{% set sha256 = "fd1624a8f0d39456423f1c3041b996dccb292efc81e30366407304960253df12" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt
  
requirements:
  build:
    - python
    - setuptools
    - attrs
    - coverage    
  run:
    - python
    - attrs
    - coverage
    
test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.searchstrategy
    - hypothesis.tools
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - git clone --depth 1 https://github.com/HypothesisWorks/hypothesis-python.git git_src
    - cd git_src
    - python -m pytest tests/cover

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
