{% set version = "3.88.3" %}


package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: 3b1aa7d49bc5f69948425d4a55b5edf4c75d79cbac72b47ab3061f55ad727b74

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
