# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.167.1"
  maturin_min: "1.9.4"
  maturin_max: "2.0"

package:
  name: hypothesis
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/h/hypothesis/hypothesis-${{ version }}.tar.gz
  sha256: 62eefcb4d2791423626e9901c3027a6e0c5ffda2ac0b44b3c7e797ab9d2d5a4c

build:
  number: 1
  skip: is_abi3 and not is_python_min
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO: cargo-auditable-wrapper${{ ".bat" if win }}
      MATURIN_PEP517_ARGS: --features pyo3/abi3
    content:
      - if: win
        then:
          - copy "%RECIPE_DIR%\cargo-auditable-wrapper.bat" "%BUILD_PREFIX%\Library\bin\cargo-auditable-wrapper.bat"
        else:
          - cp "${RECIPE_DIR}/cargo-auditable-wrapper.sh" "${BUILD_PREFIX}/bin/cargo-auditable-wrapper"
          - chmod 755 "${BUILD_PREFIX}/bin/cargo-auditable-wrapper"
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      - cd rust
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  python:
    version_independent: ${{ is_abi3 }}
    entry_points:
      - hypothesis = hypothesis.extra.cli:main

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses
    - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - pip
    - python
    - if: is_abi3
      then:
        - python-abi3
        - python ${{ python_min }}.*
  run:
    - python
    - sortedcontainers >=2.1.0,<3.0.0
tests:
  - if: is_abi3
    then:
      - python:
          imports:
            - hypothesis
            - hypothesis._native
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"
    else:
      - python:
          imports:
            - hypothesis
            - hypothesis._native
          pip_check: true
  - requirements:
      run:
        - click
        - pytest
        - if: is_abi3
          then:
            - python ${{ python_min }}.*
            - abi3audit
    script:
      - hypothesis --help
      - hypothesis --version
      - hypothesis --version | ${{ "grep -iE" if unix else "findstr /c" }} "${{ version | replace('.', '\\.') }}"
      - if: is_abi3
        then:
          - cd "${{ '$SP_DIR' if unix else '%SP_DIR%' }}/hypothesis"
          - abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} _native.${{ 'abi3.so' if unix else 'pyd' }}

about:
  summary: The property-based testing library for Python
  license: MPL-2.0
  license_file:
    - LICENSE.txt
    - rust/THIRDPARTY.yml
  homepage: https://pypi.org/project/hypothesis
  repository: https://github.com/HypothesisWorks/hypothesis
  documentation: https://hypothesis.readthedocs.io

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - ocefpaf
    - tadeu
