appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: kkB7awt8pZCDppRK3lb3H1DpxW3v7MpcovZH8apg0ee8EtlGV59C2NkV3eX4s6tYPydHFktX+rmMQoV3s8WwXxuVX7DzbpFGOSg1GwqzfnCcn0oDCWknBpccp5NIpba29XxQUAbuvadCbJQQY8d9KdxQMDD+N2/OfaApEi4i3pL2QdIwZTvFWul8Sbks2FGAs/BThQI0PkOoZy3zxApyRRpuE2cv3tAFLSPu1BiL3FGv4WtIZFhyRpU1DqzUHR9OU1h/xkyCgOaKDqXhJfv0OgWpWVaYqRCW7BL/aPQTBi1YQrxgvNDwNEqakfuKIFfkx9B+IyqI+N+kbyZxAG46/96Z3bGAtSHH0wqYEXZZ5dzPXcE/t177Gu3LmIRhjUMQx6jv0T7Tb7WoxXwdS+y4lvzZMitgG7XWredw/Aedji3vtrLhWFLZExgITSyCoLBXHxP1qoLyiee9uR5zDRNVxyFHhnSXD6mmNrZo3tYy6c1QgoZ9j3NLSP92l5P13m2Yp8LDD6YTYes64LdziQkPu9Tv8z2c4eO+v2gjL3r5fb4vAf23sYn65m44RgjQ6oCv7lX6KbVu2pc9J18nTisoCa4jQxY69rVBw/Uf2pEPISbAEakD4s34zWlP3deKqDLIdT6g/EG6XB2cu/5u32gw7OCihEmYXKooEbW6sIkiGDw=}
bot:
  automerge: true
